import { useState } from "react";
import { analyzeGap } from "../services/api";
export default function Gap({profile,resume,setGap,setPage}) {
 const [loading,setLoading]=useState(false),[data,setData]=useState(null);
 const skills=[...(profile.skillsText||"").split(",").map(x=>x.trim()).filter(Boolean),...(resume?.skills||[])];
 const run=async()=>{setLoading(true);try{const d=await analyzeGap({company:profile.targetCompany,role:profile.targetRole,skills,cgpa:profile.cgpa});setData(d);setGap(d)}finally{setLoading(false)}};
 return <Page title="Placement Gap Analysis" sub="Compare your evidence with the selected company and role."><div className="glass rounded-3xl p-7"><div className="flex flex-wrap gap-3">{skills.map(s=><span key={s} className="rounded-full bg-slate-800 px-3 py-1 text-sm">{s}</span>)}</div><button onClick={run} className="mt-7 rounded-xl bg-blue-500 px-6 py-3 font-semibold">{loading?"Analyzing...":"Analyze My Gap"}</button></div>{data&&<div className="mt-6 grid gap-5 md:grid-cols-3"><div className="glass rounded-3xl p-6 md:col-span-1"><p className="text-sm text-slate-400">Readiness</p><div className="mt-4 text-6xl font-bold">{data.readiness}%</div><p className="mt-4 text-sm text-slate-500">{data.company.company} · {data.role.role}</p></div><div className="glass rounded-3xl p-6"><h2 className="font-semibold">Strong Areas</h2>{data.matched.map(x=><p className="mt-3 text-emerald-300" key={x}>✓ {x}</p>)}</div><div className="glass rounded-3xl p-6"><h2 className="font-semibold">Needs Improvement</h2>{data.missing.map(x=><p className="mt-3 text-amber-300" key={x}>⚠ {x}</p>)}</div><div className="glass rounded-3xl p-6 md:col-span-3"><h2 className="font-semibold">Why this score?</h2>{data.reasons.map(x=><p className="mt-3 text-slate-400" key={x}>{x}</p>)}<button onClick={()=>setPage("roadmap")} className="mt-6 rounded-xl bg-violet-500 px-5 py-3 font-semibold">Create Personalized Roadmap</button></div></div>}</Page>
}
function Page({title,sub,children}){return <div className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-6xl"><p className="text-sm text-blue-400">INTELLIGENCE ENGINE</p><h1 className="mt-2 text-4xl font-bold">{title}</h1><p className="mt-2 mb-8 text-slate-400">{sub}</p>{children}</div></div>}
