import { useState } from "react";
import { getQuestion,evaluateAnswer } from "../services/api";
export default function Interview({profile}) {
 const [mode,setMode]=useState("mixed"),[difficulty,setDifficulty]=useState("adaptive"),[started,setStarted]=useState(false);
 const [q,setQ]=useState(null),[answer,setAnswer]=useState(""),[result,setResult]=useState(null),[history,setHistory]=useState([]);
 const start=async()=>{const d=await getQuestion({mode,difficulty,company:profile.targetCompany,role:profile.targetRole,previous:[]});setQ(d);setStarted(true);setResult(null);};
 const submit=async()=>{if(!answer.trim())return;const d=await evaluateAnswer({answer,question:q.question,focus:q.focus});setResult(d);setHistory([...history,{question:q.question,answer}]);setAnswer("");};
 const next=async()=>{const d=await getQuestion({mode,difficulty,company:profile.targetCompany,role:profile.targetRole,previous:history});setQ(d);setResult(null);};
 return <div className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-5xl"><p className="text-sm text-blue-400">HERO FEATURE</p><h1 className="mt-2 text-4xl font-bold">Company-Specific Shadow Interview</h1><p className="mt-2 mb-8 text-slate-400">Practice an adaptive interview for <b className="text-slate-200">{profile.targetCompany||"your target company"}</b> · {profile.targetRole||"your target role"}.</p>
 {!started?<div className="glass rounded-3xl p-7"><div className="grid gap-5 md:grid-cols-2"><label>Interview Mode<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-900 p-3"><option value="mixed">Mixed</option><option value="technical">Technical</option><option value="behavioral">Behavioral</option></select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-900 p-3"><option value="adaptive">Adaptive</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label></div><button onClick={start} className="mt-7 w-full rounded-xl bg-blue-500 px-5 py-4 font-semibold">Start Interview</button></div>:
 <><div className="glass rounded-3xl p-7"><div className="flex justify-between text-sm text-slate-500"><span>Focus: {q?.focus}</span><span>Difficulty: {q?.difficulty}</span></div><h2 className="mt-6 text-2xl font-semibold leading-relaxed">{q?.question}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows="7" placeholder="Type your answer as if you were in the interview..." className="mt-6 w-full resize-none rounded-2xl border border-slate-700 bg-slate-900 p-4 outline-none focus:border-blue-400"/>{!result?<button onClick={submit} className="mt-4 w-full rounded-xl bg-violet-500 px-5 py-3 font-semibold">Submit Answer</button>:<div className="mt-5 rounded-2xl bg-slate-900 p-6"><div className="text-4xl font-bold">{result.overall}/10</div><p className="mt-1 text-slate-500">Overall evaluation</p><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[["Technical",result.technical],["Problem Solving",result.problem_solving],["Behavioral",result.behavioral],["Communication",result.communication]].map(([a,b])=><div className="rounded-xl bg-slate-800 p-3" key={a}><p className="text-xs text-slate-500">{a}</p><b>{b}/10</b></div>)}</div><p className="mt-5"><b>Strength:</b> {result.strength}</p><p className="mt-3"><b>Weakness:</b> {result.weakness}</p><p className="mt-3 text-blue-300"><b>Improve:</b> {result.improve}</p><button onClick={next} className="mt-6 w-full rounded-xl bg-blue-500 px-5 py-3 font-semibold">Next Question</button></div>}</div></>}
 </div></div>
}
